---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 230370f
_src_path: ./
description: Litestar project example 🌠
docs: true
docsurl: https://quickplates.github.io/litestar-example
email: quickplates@mail.spietras.dev
envprefix: LITESTAR_EXAMPLE
importname: litestar_example
projectname: litestar-example
registry: true
releases: true
username: quickplates
